CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar,
  "nickname" varchar,
  "role" varchar,
  "provider" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "refresh_tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "token" varchar,
  "expired_at" datetime
);

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
